<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                       => __DIR__ . '/Module.php',
    'Admin\Controller\AuthController'    => __DIR__ . '/src/Admin/Controller/AuthController.php',
    'Admin\Controller\SuccessController' => __DIR__ . '/src/Admin/Controller/SuccessController.php',
    'Admin\Model\MyAuthStorage'          => __DIR__ . '/src/Admin/Model/MyAuthStorage.php',
    'Admin\Model\User'                   => __DIR__ . '/src/Admin/Model/User.php',
);
