<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('System ewidencji wyposażenia sal')) ?>
        <?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/style.css')  ?>
        <?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/bootstrap.css')  ?>
        <?php echo $this->headScript()->setFile($this->basePath().'/js/jquery-1.11.0.min.js','text/javascript'); ?>
        <?php echo $this->headScript()->setFile($this->basePath().'/js/rooms.js','text/javascript'); ?>
        <?php echo $this->headScript()->setFile($this->basePath().'/js/myValidator.js','text/javascript'); ?>
    </head>
    <body>
        <article>
            <header>
                    <div class="main-header">
                        <div class="main-wrapper">
                        System ewidencji wyposażenia sal dydaktycznych.
                        </div>
                    </div>
            </header>
            <div class="main-wrapper">
                <nav>
                    <div class="nav">
                        <a href="<?php echo $this->url('rooms_segment', 
                                array('action' => 'list')); ?>"><?php
                                echo $this->translate("Sale dydaktyczne"); ?></a>
                        <!--<a href="<?php echo $this->url('rooms_segment', 
                                array('action' => 'info')); ?>"><?php
                                echo $this->translate("Informacje"); ?></a>-->
                    </div>
                </nav>
                
                <article>
                    <div class="fash_message">
                        <?php echo $this->flashMessenger()->render(); ?>
                    </div>
                </article>

                <article>
                    <div class="row" id="content_wrapper">
                        <div class="col-md-8" id="content">
                            <div style="padding-right:20px">
                                <?php echo $this->content; ?>
                            </div>
                        </div>
                        <div class="col-md-4" id="subnav">
                            <nav><?php echo $this->subnav; ?></nav>
                        </div>
                    </div>
                </article>

                <footer>
                    <div class="footer">
                        <?php echo $this->translate('Politechnika Rzeszowska'); ?>
                    </div>
                </footer>
            </div>
        </article>
    </body>
</html>
