<header>
    <div class="header"><?php echo $this->translate('Informacje o sali')?></div>
</header>

<div class="roomDetails">
    <div class="row">
        <div class="field"><?php echo $this->translate('Numer sali'); ?>:</div>
        <div class="val"><?php echo $room->number ?></div>
    </div>
    
    <div class="row">
        <div class="field"><?php echo $this->translate('Nazwa sali'); ?>:</div>
        <div class="val"><?php echo $room->name ?></div>
    </div>
    
    <div class="row">
        <div class="field"><?php echo $this->translate('Budynek') ?>:</div>
        <div class="val"><?php echo $room->building ?></div>
    </div>
    
    <div class="row">
        <div class="field"><?php echo $this->translate('Opiekun sali') ?>:</div>
        <div class="val"><?php echo $room->attendant ?></div>
    </div>
    
    <div class="row">
        <div class="field"><?php echo $this->translate('Ilość stanowisk') ?>:</div>
        <div class="val"><?php echo $room->posts ?></div>
    </div>
    
    <div class="row">
        <div class="field"><?php echo $this->translate('Ilość wyposażenia') ?>:</div>
        <div class="val"><?php echo $room->getEquipmentCount(); ?></div>
    </div>
</div>

<h2><?php echo $this->translate('Lista wyposażenia') ?></h2>

<p><em><?php echo sprintf($this->translate('Ilość sprzętu:  %s'), $equipments->count()); ?></em></p>

<?php foreach ( $equipments as $equip ): ?>
    <?php echo $this->partial('equipment_partial', array('equipment' => $equip)); ?>
<?php endforeach; ?>
